### ISSUE TITLE
Can I use delivery-cli instead?

### ISSUE THREAD

**Issue by docwhat** [chef-cookbooks/pcb#2]
Is the delivery server needed? Or can I use the `delivery-cli` instead?

@stephenlauck was interested in this too.

**Comment by afiune** [comment]
@docwhat I a not sure I understand your question but I can try to explain how we are using `pcb` and maybe that can help...

The `delivery-cli` internally uses `pcb` to generate the `build-cookbook` that is stored at `.delivery/build-cookbook`... This is been done by the `delivery init` command.

Now if the command is run inside a cookbook, then `pcb` will detect that and depend immediately on [delivery-truck](https://github.com/chef-cookbooks/delivery-truck) (that is our build-cookbook for chef cookbooks). 

It is possible to use `pcb` out of the `delivery-cli`? Yes! But you have to have `ChefDK` installed. You can use it like this:

```
$ chef generate cookbook build-cookbook -g /repo/pcb
```

Does that help you?

**Comment by afiune** [comment]
I think the question was answered. If not please ping me on Slack or just re-open this issue! :smile:

**Comment by docwhat** [comment]
@stephenlauck asked me to open this. I pinged him but I guess he's out?
